// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../core/resource';
import * as CompletionsAPI from './completions';
import {
  Annotation,
  ChatCompletionAssistantMessageParam,
  ChatCompletionAudio,
  ChatCompletionAudioParam,
  ChatCompletionContentPartAudioParam,
  ChatCompletionContentPartFileParam,
  ChatCompletionContentPartImageParam,
  ChatCompletionContentPartRefusalParam,
  ChatCompletionContentPartTextParam,
  ChatCompletionDeveloperMessageParam,
  ChatCompletionFunctionMessageParam,
  ChatCompletionFunctions,
  ChatCompletionMessage,
  ChatCompletionMessageCustomToolCall,
  ChatCompletionMessageToolCall,
  ChatCompletionSystemMessageParam,
  ChatCompletionTokenLogprob,
  ChatCompletionToolMessageParam,
  ChatCompletionToolParam,
  ChatCompletionUserMessageParam,
  Choice,
  ChoiceDelta,
  ChoiceDeltaFunctionCall,
  ChoiceDeltaToolCall,
  ChoiceDeltaToolCallFunction,
  ChoiceLogprobs,
  ChunkChoice,
  Completion,
  CompletionCreateParams,
  CompletionCreateParamsNonStreaming,
  CompletionCreateParamsStreaming,
  CompletionRequest,
  CompletionTokensDetails,
  CompletionUsage,
  Completions,
  Custom,
  Function,
  FunctionCall,
  InputTokenDetails,
  PredictionContent,
  PromptTokensDetails,
  Reasoning,
  StreamChunk,
  ThinkingConfigDisabled,
  ThinkingConfigEnabled,
  ToolChoice,
  ToolChoiceAny,
  ToolChoiceAuto,
  ToolChoiceNone,
  ToolChoiceTool,
  TopLogprob,
  URLCitation,
} from './completions';

export class Chat extends APIResource {
  completions: CompletionsAPI.Completions = new CompletionsAPI.Completions(this._client);
}

Chat.Completions = Completions;

export declare namespace Chat {
  export {
    Completions as Completions,
    type Annotation as Annotation,
    type ChatCompletionAssistantMessageParam as ChatCompletionAssistantMessageParam,
    type ChatCompletionAudio as ChatCompletionAudio,
    type ChatCompletionAudioParam as ChatCompletionAudioParam,
    type ChatCompletionContentPartAudioParam as ChatCompletionContentPartAudioParam,
    type ChatCompletionContentPartFileParam as ChatCompletionContentPartFileParam,
    type ChatCompletionContentPartImageParam as ChatCompletionContentPartImageParam,
    type ChatCompletionContentPartRefusalParam as ChatCompletionContentPartRefusalParam,
    type ChatCompletionContentPartTextParam as ChatCompletionContentPartTextParam,
    type ChatCompletionDeveloperMessageParam as ChatCompletionDeveloperMessageParam,
    type ChatCompletionFunctionMessageParam as ChatCompletionFunctionMessageParam,
    type ChatCompletionFunctions as ChatCompletionFunctions,
    type ChatCompletionMessage as ChatCompletionMessage,
    type ChatCompletionMessageCustomToolCall as ChatCompletionMessageCustomToolCall,
    type ChatCompletionMessageToolCall as ChatCompletionMessageToolCall,
    type ChatCompletionSystemMessageParam as ChatCompletionSystemMessageParam,
    type ChatCompletionTokenLogprob as ChatCompletionTokenLogprob,
    type ChatCompletionToolMessageParam as ChatCompletionToolMessageParam,
    type ChatCompletionToolParam as ChatCompletionToolParam,
    type ChatCompletionUserMessageParam as ChatCompletionUserMessageParam,
    type Choice as Choice,
    type ChoiceDelta as ChoiceDelta,
    type ChoiceDeltaFunctionCall as ChoiceDeltaFunctionCall,
    type ChoiceDeltaToolCall as ChoiceDeltaToolCall,
    type ChoiceDeltaToolCallFunction as ChoiceDeltaToolCallFunction,
    type ChoiceLogprobs as ChoiceLogprobs,
    type ChunkChoice as ChunkChoice,
    type Completion as Completion,
    type CompletionRequest as CompletionRequest,
    type CompletionTokensDetails as CompletionTokensDetails,
    type CompletionUsage as CompletionUsage,
    type Custom as Custom,
    type Function as Function,
    type FunctionCall as FunctionCall,
    type InputTokenDetails as InputTokenDetails,
    type PredictionContent as PredictionContent,
    type PromptTokensDetails as PromptTokensDetails,
    type Reasoning as Reasoning,
    type StreamChunk as StreamChunk,
    type ThinkingConfigDisabled as ThinkingConfigDisabled,
    type ThinkingConfigEnabled as ThinkingConfigEnabled,
    type ToolChoice as ToolChoice,
    type ToolChoiceAny as ToolChoiceAny,
    type ToolChoiceAuto as ToolChoiceAuto,
    type ToolChoiceNone as ToolChoiceNone,
    type ToolChoiceTool as ToolChoiceTool,
    type TopLogprob as TopLogprob,
    type URLCitation as URLCitation,
    type CompletionCreateParams as CompletionCreateParams,
    type CompletionCreateParamsNonStreaming as CompletionCreateParamsNonStreaming,
    type CompletionCreateParamsStreaming as CompletionCreateParamsStreaming,
  };
}
